version: '3'

services:
  # MongoDB 服务
  mongodb:
    image: mongo:latest
    container_name: learngenie-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_DATABASE: learngenie
    ports:
      - "27017:27017"
    networks:
      - learngenie-network

  # 后端服务
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: learngenie-backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://learngenie_app:app_password@mongodb:27017/learngenie
      - JWT_SECRET=your_jwt_secret_key
      - PORT=5000
      - NODE_ENV=production
      - AI_API_KEY=your_ai_api_key
    ports:
      - "5000:5000"
    networks:
      - learngenie-network

  # AI 模型服务
  ai-model:
    build:
      context: ../ai_models
      dockerfile: Dockerfile
    container_name: learngenie-ai-model
    restart: always
    environment:
      - DEEPSEEK_API_KEY=your_deepseek_api_key
      - QWEN_API_KEY=your_qwen_api_key
    ports:
      - "5001:5001"
    networks:
      - learngenie-network

  # 前端服务
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: learngenie-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - learngenie-network

networks:
  learngenie-network:
    driver: bridge

volumes:
  mongodb_data: 